repository:
  name: secureblog
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "SecureBlog – Build • Verify • Attest • Deploy"
          - "Supply Chain Security"
          - "CodeQL"
          - "Link Audit"
          - "Verify Live Security"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
        dismiss_stale_reviews: true
        require_last_push_approval: true
      restrictions: null
      required_linear_history: true
      lock_branch: false
      allow_force_pushes: false
      allow_deletions: false
      required_signatures: true