# Cloudflare Pages/Workers Sites Configuration with Edge Security Gates
name = "secureblog"
main = "scripts/edge-runtime-gates.js"
compatibility_date = "2024-08-31"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist/public"

# Bind static assets for the improved Worker
[[env.production.services]]
binding = "ASSETS"
service = "secureblog-assets"

[env.production]
vars = { ENVIRONMENT = "production" }
route = "secureblog.com/*"

[env.staging]
vars = { ENVIRONMENT = "staging" }
route = "staging.secureblog.com/*"

# R2 bucket for static assets
[[r2_buckets]]
binding = "STATIC_ASSETS"
bucket_name = "secureblog-static"

# Security headers applied at edge
[env.production.vars]
CSP = "default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'"
REFERRER_POLICY = "no-referrer"
PERMISSIONS_POLICY = "accelerometer=(), battery=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()"
COOP = "same-origin"
COEP = "require-corp"
CORP = "same-origin"

# Enhanced rate limiting configuration for edge security
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1"
simple = { limit = 60, period = 60 }  # 60 requests per minute

# Additional security configuration
[env.production.vars]
# Override existing vars with enhanced security settings
ENVIRONMENT = "production"
SECURITY_MODE = "strict"
MAX_REQUEST_SIZE = "1024"  # 1KB limit as specified
MAX_URL_LENGTH = "2048"
MAX_QUERY_LENGTH = "256"
RATE_LIMIT_ENABLED = "true"
BOT_PROTECTION_ENABLED = "true"
GEOGRAPHIC_BLOCKING = "false"  # Set to "true" and configure if needed
ASN_BLOCKING = "false"        # Set to "true" and configure if needed

# Ultra-strict CSP for zero JavaScript (but usable for static content)
CSP = "default-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'; script-src 'none'; connect-src 'none'; img-src 'self' data:; style-src 'self'; font-src 'self'; object-src 'none'; media-src 'self'; worker-src 'none'; manifest-src 'self'; frame-src 'none'; upgrade-insecure-requests; block-all-mixed-content"
REFERRER_POLICY = "strict-origin-when-cross-origin"
PERMISSIONS_POLICY = "accelerometer=(), battery=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=(), bluetooth=(), autoplay=(), fullscreen=(), picture-in-picture=()"
COOP = "same-origin"
COEP = "require-corp"
CORP = "same-origin"