name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Get dependencies
      run: go mod download
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
    
    - name: Security Audit
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec ./...
    
    - name: Build Blog
      run: |
        go build -o secureblog cmd/main_v2.go
        ./secureblog -content=content -output=build
    
    - name: Verify Build
      run: |
        test -f build/index.html
        test -f build/integrity.txt
        test -f build/_headers
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/