name: CI (secure)
on:
  push:
    branches: [ "**" ]
  pull_request:

permissions:
  contents: read
  security-events: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: "1.23.x"  # current stable
          check-latest: true

      - name: Go cache
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Verify formatting
        run: |
          set -euo pipefail
          fmtout=$(gofmt -s -l . || true)
          if [ -n "$fmtout" ]; then
            echo "gofmt differences in:"
            echo "$fmtout"
            exit 1
          fi

      - name: Staticcheck
        uses: dominikh/staticcheck-action@b21d3b1a8c3ef3f5f852896b1341ebee4550c1c1 # v1.3.1
        with:
          version: "latest"

      - name: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          go-version-input: "1.23"
          args: ./...

      - name: Secrets scan (gitleaks)
        uses: gitleaks/gitleaks-action@f9d29bd1598e73c7387e5f3c6311fd4e7e3c0367 # v2.3.7
        with:
          args: --no-banner --redact

      - name: Secure build (sandboxed)
        run: bash ./build-sandbox.sh

      - name: No-JS regression guard
        run: bash ./.scripts/nojs-guard.sh dist

      - name: Link checker
        run: bash ./scripts/linkcheck.sh dist

      - name: Upload built site (PR previews etc.)
        if: always()
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: site-dist
          path: dist