name: deploy-pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e31de5234b664ca3f0ed09e5ce0d6de0c5d0fc1 # actions/checkout@v4

      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build (sandboxed)
        run: |
          chmod +x ./build-sandbox.sh || true
          ./build-sandbox.sh

      - name: No-JS regression guard
        run: bash .scripts/security-regression-guard.sh

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: secureblog
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}