name: SLSA Provenance
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          
      - name: Build
        run: |
          # Build with security flags
          CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o secureblog .
          
          # Create dist directory
          mkdir -p dist
          cp -r static templates content dist/ 2>/dev/null || true
          cp secureblog dist/
          
          # Package artifacts
          tar -czf dist.tar.gz -C dist .
          
      - name: Generate hashes
        id: hash
        run: |
          # Generate SHA256 hashes
          sha256sum dist.tar.gz > checksums.txt
          
          # Set output for SLSA
          echo "digests=$(sha256sum dist.tar.gz | base64 -w0)" >> "$GITHUB_OUTPUT"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: |
            dist.tar.gz
            checksums.txt
          retention-days: 5

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true
      
  verify:
    needs: [build, provenance]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Install SLSA verifier
        uses: slsa-framework/slsa-verifier/actions/installer@v2.6.0
        
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          
      - name: Download provenance
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.provenance.outputs.provenance-name }}
          
      - name: Verify provenance
        run: |
          slsa-verifier verify-artifact \
            --provenance-path ${{ needs.provenance.outputs.provenance-name }} \
            --source-uri github.com/${{ github.repository }} \
            dist.tar.gz
            
      - name: Display verification
        run: |
          echo "✅ SLSA Provenance Verification Successful"
          echo "Artifact: dist.tar.gz"
          echo "SHA256: $(sha256sum dist.tar.gz | cut -d' ' -f1)"