name: provenance

on:
  workflow_run:
    workflows: [ "deploy-pages", "ci-security" ]
    types: [ completed ]

permissions:
  contents: write
  id-token: write

jobs:
  package-dist:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: dist
      - name: Tar site
        run: tar -C dist -czf dist.tar.gz .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-tarball
          path: dist.tar.gz

  slsa-provenance:
    needs: package-dist
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-tarball
          path: .
      - name: Generate SLSA provenance
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
        with:
          artifact_path: dist.tar.gz
          attestation_name: secureblog-dist