name: provenance
on:
  push:
    branches: [ "main" ]
permissions:
  id-token: write
  contents: read
jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-go@v5
        with: { go-version: "1.22.x" }

      - name: Build site artifacts
        run: |
          make build
          tar -C build -czf site.tar.gz .

      - name: Generate provenance predicate
        run: |
          cat > provenance.json <<'JSON'
          {
            "predicateType": "https://slsa.dev/provenance/v1",
            "buildType": "secureblog-go-static",
            "buildConfig": {
              "repo": "${{ github.repository }}",
              "commit": "${{ github.sha }}",
              "runner": "github-actions",
              "generator": "secureblog"
            }
          }
          JSON

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.6.0

      - name: Attest site tarball (keyless)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign attest-blob --yes \
            --predicate provenance.json \
            --type slsaprovenance \
            site.tar.gz > site.tar.gz.attestation

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: secureblog-site+attestation
          path: |
            site.tar.gz
            site.tar.gz.attestation
            provenance.json