name: release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write

jobs:
  build-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Build (secure)
        run: make -f Makefile.security build

      - name: Generate SBOM (SPDX)
        uses: anchore/sbom-action@v0
        with:
          path: .
          output-file: sbom.spdx.json
          format: spdx-json

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Sign dist/ (keyless OIDC)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          find dist -type f -print0 | xargs -0 -I{} cosign sign-blob --yes {} \
            --output-signature {}.sig --output-certificate {}.pem

      - name: Attest build provenance (SLSA-ish)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign attest --predicate <(jq -n \
            --arg built "$(date -u +%FT%TZ)" \
            --arg builder "github-actions" \
            '{buildType:"https://slsa.dev/provenance/v1", buildStartedOn:$built, builder:$builder}') \
            --type https://slsa.dev/provenance/v1 \
            --yes dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**
            sbom.spdx.json
            dist/**/*.sig
            dist/**/*.pem