name: Release
on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  attestations: write
  id-token: write

concurrency:
  group: rel-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
          check-latest: true

      - name: Secure build (sandboxed)
        run: bash ./build-sandbox.sh

      - name: No-JS regression guard
        run: bash ./.scripts/nojs-guard.sh dist

      - name: Link checker
        run: bash ./scripts/linkcheck.sh dist

      - name: Pack dist
        run: |
          tar -C dist -czf dist.tgz .

      - name: Generate SBOM (SPDX)
        uses: anchore/sbom-action@v0
        with:
          path: ./dist
          artifact-name: sbom.spdx.json

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest build provenance (SLSA/in-toto)
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "dist.tgz"