name: Release
on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  attestations: write
  id-token: write

concurrency:
  group: rel-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.2

      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: "1.23.x"
          check-latest: true

      - name: Secure build (sandboxed)
        run: bash ./build-sandbox.sh

      - name: No-JS regression guard
        run: bash ./.scripts/nojs-guard.sh dist

      - name: Link checker
        run: bash ./scripts/linkcheck.sh dist

      - name: Pack dist
        run: |
          tar -C dist -czf dist.tgz .

      - name: Generate SBOM (SPDX)
        uses: anchore/sbom-action@fc46e51fd3cb168ffb36ec72c5bcf7e3e52b3b91 # v0.17.9
        with:
          path: ./dist
          artifact-name: sbom.spdx.json

      - name: Create GitHub release
        uses: softprops/action-gh-release@e7a8f85e1c69a9ca6ba914d1d0e05ba8254ed7eb # v2.1.0
        with:
          files: |
            dist.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest build provenance (SLSA/in-toto)
        uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018 # v1.4.4
        with:
          subject-path: "dist.tgz"